/**
 * env var から landing/config.js を生成する。
 *
 * 使用する env var:
 *   STRIPE_PAYMENT_LINK_INDIVIDUAL  個人プランの Stripe Payment Link
 *   STRIPE_PAYMENT_LINK_CORPORATE   法人プランの Stripe Payment Link
 *
 * Vercel など静的ホスティングでは Build Command としてこれを実行する。
 *   node build-config.mjs
 *
 * env が未設定でも失敗しない (config.js は空設定で出力 → CTA は「準備中」表示)。
 * 秘密情報ではないため config.js の内容はクライアントに配信される。
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

const individual = process.env.STRIPE_PAYMENT_LINK_INDIVIDUAL || "";
const corporate = process.env.STRIPE_PAYMENT_LINK_CORPORATE || "";

const config = {
  stripePaymentLinkIndividual: individual,
  stripePaymentLinkCorporate: corporate,
};

const body =
  "/* AUTO-GENERATED by build-config.js — do not edit. */\n" +
  "window.KDP_FACTORY_CONFIG = " +
  JSON.stringify(config, null, 2) +
  ";\n";

await writeFile(join(here, "config.js"), body, "utf8");

const note = (v) => (v ? "set" : "MISSING (CTA shows '準備中')");
console.log("[build-config] landing/config.js written");
console.log("  STRIPE_PAYMENT_LINK_INDIVIDUAL:", note(individual));
console.log("  STRIPE_PAYMENT_LINK_CORPORATE :", note(corporate));
